language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

script:
  - ./gradlew build

before_install:
  - wget http://services.gradle.org/distributions/gradle-5.4.1-bin.zip
  - unzip -qq gradle-5.4.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.4.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  - chmod +x gradlew

after_success:
  - ./upload-apk.sh