language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

before_install:
  - wget http://services.gradle.org/distributions/gradle-5.4.1-bin.zip
  - unzip -qq gradle-5.4.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.4.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script:
  - gradle build

after_success:
  - sh publish.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file: "app/build/outputs/apk/debug/app-debug.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: dev
    repo: hazae41/sweet-ipfs